name: Merge PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-slim
    if: github.actor == 'dependabot[bot]' && github.repository == 'josh/trakt-plex-sync'

    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0

      - name: Enable auto-merge
        if: steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
